#pragma once

// Minimal RIFF/WAVE reader.
//
// OpenAL takes raw PCM and has no file loading of its own (ALUT, which used to
// provide it, is long deprecated). All the project's audio is generated by
// tools/generate_audio.py as 16-bit PCM wav, so this only needs to handle that
// one shape -- and it says so loudly rather than guessing when handed anything
// else.
//
// Deliberately free of any OpenAL dependency so it can be unit tested on a
// machine with no sound device, which is every CI runner.

#include <cstdint>
#include <string>
#include <vector>

namespace hu {

struct WavData {
    int channels = 0;
    int sampleRate = 0;
    int bitsPerSample = 0;
    std::vector<std::uint8_t> samples;   // Interleaved little-endian PCM.

    bool valid() const {
        return channels > 0 && sampleRate > 0 && bitsPerSample == 16 && !samples.empty();
    }

    std::size_t frameCount() const {
        const int bytesPerFrame = channels * (bitsPerSample / 8);
        return bytesPerFrame > 0 ? samples.size() / static_cast<std::size_t>(bytesPerFrame) : 0;
    }

    float durationSeconds() const {
        return sampleRate > 0 ? static_cast<float>(frameCount()) / static_cast<float>(sampleRate)
                              : 0.0f;
    }
};

// Reads a 16-bit PCM wav. Returns false and leaves `out` untouched on any
// problem, writing the reason to `error` when it is non-null.
bool loadWav(const std::string& path, WavData& out, std::string* error = nullptr);

// Parses an in-memory RIFF buffer. Exposed separately so tests can feed it
// malformed input without touching the filesystem.
bool parseWav(const std::uint8_t* data, std::size_t size, WavData& out,
              std::string* error = nullptr);

} // namespace hu
